### ISSUE TITLE
NPM Release

### ISSUE THREAD

**Issue by QingShan-Xu** [zen-fs/worker#3]
Hello author, do you have any plans to release this package on npm?

**Comment by dr-vortex** [comment]
@QingShan-Xu,

Yes, it should be released in the next week or so.

**Comment by dr-vortex** [comment]
@QingShan-Xu,

The package has been released as `@zenfs/port` (since it is not restricted to workers). Please note that it is unstable so you may encounter bugs.

**Comment by QingShan-Xu** [comment]
._. Thank you, I will use it in the near future
